name: whatsapp-send-service
region: nyc

services:
  - name: api
    github:
      repo: your-github-username/whatsapp-send-service
      branch: main
      deploy_on_push: true
    
    source_dir: /
    
    build_command: npm install
    run_command: node server.js
    
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    http_port: 8080
    
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: USE_PAIRING_CODE
        value: "true"
      - key: LOG_LEVEL
        value: info
    
    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
